version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
    image: app:hhnsu
    container_name: hhnsu_bot_container
    command: python3 app/main.py
    depends_on:
      - db 
  db:
    image: postgres
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db



