version: "3"
services:
  # app:
  #   build: .
  #   volumes:
  #     - .:/app
  #   image: app:hhnsu
  #   container_name: app_container
  #   command: python main.py
  #   depends_on:
  #     - db 
  db:
    image: postgres
    environment:
        POSTGRES_DB: hhnsu
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    container_name: hhnsu_db
    ports:
       - "127.0.0.1:5432:5432" 


# # version: "3"
# # services:
# #   db:
# #     image: postgres
# #     environment:
# #       POSTGRES_USER: postgres
# #       POSTGRES_PASSWORD: postgres
# #     ports:
# #        - "127.0.0.1:5432:5432" 
